language: php
php:
  - "7.2"

before_install:
  - pecl install xdebug

install:
  - travis_retry composer install --no-suggest --prefer-dist -n -o


script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml


after_success:
  - vendor/bin/php-coveralls -v